### ISSUE TITLE
User Items #

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#1779]
It seems that the User Items counter is somehow not always updating/working. Look at the capture: 4 blocked users, with their posting deleted. It still shows to 3 of them they have # items.

![screenshot_1](https://cloud.githubusercontent.com/assets/4467158/5350317/0e491d5c-7f4c-11e4-8635-3799273c3561.png)

**Comment by conejoninja** [comment]
Can not reproduce the issue, could you please specify how to reproduce this issue?

I tried different combinations of block/unblock/delete/post both items and users

**Comment by eurobank** [comment]
Well it seems that you can't reproduce any of the reported bugs and problemns by me. And it is very hard to keep up with this, personally. Needs a lot of time and effort and to remember what the problem was months back, after updates and everything.

**Comment by conejoninja** [comment]
I'm sorry, we work as hard as we can't, and we review issues as we could.

I tried with blocked item -> block / unblock the user
unblock items -> block / unblock the user
mix of blocked/non blocked items -> block / unblock the user

It worked fine everytime, I'm not sure why as your picture shows something is clearly wrong.

It's not true we can not reproduce all of your issues, we're currently reviewing this #1692
As soon as I learned it happens with some webservers I reopened it.

**Comment by dev-101** [comment]
There is definitively a problem here, numbers are wrong. For example, if item is deleted by user, the count is not decreased by -1. Probably there are other omissions, since on one of my setups I have a user with 0 items, where it has in fact 1. This may be caused by Butler plugin, which I was testing a while ago, but now it is removed.

Although, this is not a critical issue, Conejo can you reopen it at least until it is examined in more detail and confirmed / resolved?
