### ISSUE TITLE
alerts should not display user's own items that match alert

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1832]
Hi,
currently if a user creates an alert, and an item which contains the same word, it will be notified about it and listed in the user's alert, but should not. Although, the real-world case scenario for this to happen is low, we currently do not filter the userId or exclude it in the search.

![osclass-alerts-issue](https://cloud.githubusercontent.com/assets/5383059/6145481/79d1194e-b1e2-11e4-9cb6-3d13eb560628.png)

**Comment by dev-101** [comment]
Thanks Daniel :)

**Comment by conejoninja** [comment]
This only fix the user's dashboard, not the emails sent to the users. The reason is that actually the alerts are sent in "batches", let's say 10 users subscribed to "cars" listings, it's the same search, and it's performed only ONCE in the database, and sent the same results to 10 users. 

If we "fix" this, and make every alert not to include the users' own listings, then we'll have 10 different searches hitting the database.

**Comment by dev-101** [comment]
Thanks for explaining,
not to worry, this is exactly what I needed, not minding the emails really.

:beer:
