### ISSUE TITLE
Optimize user registration if there're ads with the same email

### ISSUE THREAD

**Issue by conejoninja** [osclass/Osclass#1843]
In case a user register and there are ads with the same email, all those items are "transferred" into the user's account. This is done one by one, and has to be done in batches, it could kill the server if there're a few thousands ads with one email.

UserActions.php

Also, increase user's stats

**Comment by Adyyda** [comment]
This bug has been fixed?

**Comment by conejoninja** [comment]
It's still open

**Comment by Adyyda** [comment]
That is bad since 5 months have passed. And looks to be a big issue.

**Comment by conejoninja** [comment]
It's not a big issue as this is not common.

**Comment by Adyyda** [comment]
I see. Because there are not many big sellers i assume. Anyway, 5+ months for a know issue is a big period of time. 
May i ask if osclass will be improved beyond this point, where it is now, or you will focus on other projects? Because it seems to be almost dead except the market area (from where you get some income) and forum area. Don't get me wrong. You did a fantastic work on most areas but in others we should have improvements.

**Comment by conejoninja** [comment]
Yes, we continue working on the core.

**Comment by Adyyda** [comment]
Ok. Good to know. Can you tell me if there is  a mention anywhere regarding what improvements/fixes will we have for the next version? A roadmap if you wish. I didn't manage to find such information.
