### ISSUE TITLE
More clever pattern search?

### ISSUE THREAD

**Issue by adrienrn** [osclass/Osclass#2059]
While working for a client and digging around the pattern search, I've realized the current implementation **only match whole word**, not partial words.

An item named 'Psychology for the dummies - part 1' will appear for the 'Psychology' pattern but not for the 'Psycho' pattern. Note that you can use 'Psycho*' to match partial words but it's not natural to the common user. Those who don't code - :).
### Current situation

For reference, this is the SQL used for the search pattern.
https://github.com/osclass/Osclass/blob/v3.6.1/oc-includes/osclass/model/Search.php#L918

``` sql
MATCH(d.s_title, d.s_description) AGAINST('%s' IN BOOLEAN MODE)", $this->sPattern) );
```

Unfortunately, the `MATCH ... AGAINST` mysql operator only matches whole word.
### Proposition

As stated in [this StackOverflow thread](http://stackoverflow.com/questions/37711370/mysql-how-to-get-search-results-with-accurate-relevance), we could make this search pattern feature a bit more clever and a bit more natural to users. 

``` sql
select id, name
from subjects
where name like concat('%', @search, '%')
order by 
  name like concat(@search, '%') desc,
  ifnull(nullif(instr(name, concat(' ', @search)), 0), 99999),
  ifnull(nullif(instr(name, @search), 0), 99999),
  name;
```

What do you think?

As explained, this form of query will match:

> First those that have it at the beginning, then those that have it after a blank, then by the position of the occurrence, then alphabetical.
### Note

LIKE vs. MATCH ... AGAINST:
http://stackoverflow.com/questions/792875/which-sql-query-is-better-match-against-or-like

If title and description are not indexed, they might need to be for LIKE to be efficient.
---

Thanks!

**Comment by dev-101** [comment]
Don't go with LIKE, especially %...% form, as it does a full table scan each time you perform a search. It will also return a lot of unrelated results (which is bad in it's own way, if not worse).

Osclass uses MyISAM because of FULLTEXT indexes benefits (innoDB is getting there... but according to my benchmarks, not quite there yet), which brings performance at least as a factor of 20 (pattern%) and 30 (%pattern%) (my own db with 2 million real records, depends on lot of factors, systems, configs... not counting php side).

However, I agree that current implementation of FULLTEXT in Osclass is not optimal. For example, we use boolean mode, which is great, but it also supports relevance ordering, which Osclass does not use and benefit from. Also, wildcard could be implemented into the core, as it practically does not affect performance at all - but, it may affect search results, depending on what user expects to find. This is why relevance should be implemented.

Check this forum topic:

http://forums.osclass.org/general-help/important-how-to-have-a-really-funcional-search/

where member **teseo** added some cool modification functions outside the core, however, adding relevance complicates a lot of things, none of the proposed solutions there is bug-proof in my test systems using multi-language inputs.

This is why I would like that Osclass Team take a good look into it and make it officially part of the search model, even with some admin preferences tweaks, like wildcard enabled.

Old, but still good read:
http://www.slideshare.net/billkarwin/practical-full-text-search-with-my-sql

**Comment by markuspmeyer** [comment]
Maybe an option could be a complete external solution like:

http://sphinxsearch.com/docs/current.html

With the drawback of additional installation of packages onto the system

**Comment by garciademarina** [comment]
right now we don't have plans to include wildcards on search pattern. 

it can be implemented like dev101 points using hooks via plugin for example. 
http://forums.osclass.org/general-help/important-how-to-have-a-really-funcional-search/msg112640/#msg112640
