### ISSUE TITLE
OSC_RUN_HOOK no return value?

### ISSUE THREAD

**Issue by andrewpros** [osclass/Osclass#2097]
Hi.

Is there any important reason for osc_run_hook not returning value from call_user_func_array call?

https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/helpers/hPlugins.php#L34

If it would just return it like in osc_apply_filter then echo won't be needed, which for now can be a problem sometimes.

**Comment by conejoninja** [comment]
Because not always you need a return value. with filters, you receive an object, transform it and pass it to the next plugin, with hooks you don't receive anything, nor have the obligation to return it.

How is "echo" a problem? and how returning something (and maybe echoing it later) will fix your issue?

**Comment by andrewpros** [comment]
@conejoninja 

How this is closed even without discussing? I cannot simply agree.

You are using a call_user_func_array function which can return values, but you strip it from that functionality without apparent reason at all.

So i was asking for a valid argument why not, why would someone on purpose strip functionality that could be used and gain nothing from removing it?

But the other way around, someone might want it, right? Depends on the project and programmer needs.

You say that return value is not always needed, right, but i can say the exact opposite, that it is needed when you want it, and both of us are right.

This should be changed, it is literally just one word and give me and others more options to ease making code,  call_user_func_array do not obligate anyone to return anything, if it is a void function, you don't need to return anything and can still use echo if you want.

This change doesn't break anything it only adds possibilities, so i would like to propose to make it return the value if there isn't any important reason to do it.

You were asking for "echo" problem explanation, here are my arguments

- if it doesn't break and change anything, but gives more possibilities to write code the way i or others want to, then why not, doesn't hurt anybody
- osc_run_hook is not only used in views and can be used everywhere, so from pure code architecture side it could be used only in code (i want that), not even in any view, echo is just not needed in that situations and can't be used if the script want a return value to work with but it is not a view
- interoperability with other plugins, the same as above, want to use one plugin data and/or functions in another, don't want to echo anything, but don't want to check every time if the other plugin is enabled, i can just simply osc_run_hook and if it is not existing or enabled, nothing happens, yet i can return data if it is
- same function used in many places, needed in view, needed in code, need to write it twice for different usage, why? If it is used in view, echo will be used, but then the echo would be also in purely code usage and it just can't be, or you need to make some osc_run_hook proxy functions that only calls echo on the right function, it complicates things
- the above also connects with just returning the data for further processing and not echoing it immediately, later i'm echoing it, but changed, and many times it is needed to make it directly in view file code, architecture can't not always be like we would want to

And that's it, i think that this points are valid reasons to add return to osc_run_hook function, isn't it?

Is there anything what would break or change if osc_run_hook would return values?

**Comment by conejoninja** [comment]
It was closed because the functionality you are looking for are "filters", they already exists, if you want to return a value, use a filter.

Making hooks to return data, will break most of the code and plugins, as the return data should be a parameter of the next hooked plugin/function (on same hook) and current plugins are not compatible with it. To make it clear, several functions could be attached to the same hook, they will be called sequentially, one after the other, if a function does not return anything, the next function receives nothing, so you are, at least, required to return whatever you received, which is what filters do. With filters, the developer knows he has to return something, with hooks that "may or may not" return anything, someone could forgot about it, "breaking" the rest of the code. So we have two ways: hooks (do not return anything) and filters (must return something). I think that allowing hooks to return something (or not) will only make it more complex, if we force hooks to return something... then we convert all hooks into filters.

If you want to change a specific hook to a filter, then we could discuss which one and how.

**Comment by andrewpros** [comment]
Sorry i didn't response earlier. I was just focused on the hooks, the documentation isn't that good, never used a filter before, but you are right, you should tell me that in the first place :-) that filters is what i'm looking for.
