### ISSUE TITLE
package dependency/improvement

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2098]
Hm, just wondering if we could improve this:

http://forums.osclass.org/general-help/admin-area-osclass-stops-working-when-i-download-server-site!/

So, basically, instead of 500 throw a warning and have some basic diagnostic page with checklist (php version, mysql, necessary libs etc.)

**Comment by conejoninja** [comment]
Error 500 are generated at server level, not something we could handle at PHP level :(

**Comment by dev-101** [comment]
Hi Conejo,
True, sometimes when server returns 500, PHP also manages to write the error (before things go south).

In this case, user (in forums) did not post any additional info (e.g. error log), but I think he must have something as a clue.

Thanks anyway ;)

**Comment by dev-101** [comment]
Just re-read the topic, his admin side was working (sort of), but had problems with some operations.
I was thinking to add warning messages above (like flash, or similar) that some components are missing.
Before 500 errors and all.

**Comment by conejoninja** [comment]
The dependencies of Osclass are very little (gd, mysqli & php >=5.6 - and some folders has to be writable-) and checking them in every oc-admin load (or at least when you access the dashboard) seems unnecessary to me (if mysqli is missing you can not log into the admin), PHP works fine for >= 5.3 (but we do ask for 5.6 for new installations) and you should be using PHP 7 anyway, so we only have to check for GD, the % of people who will have this issue seems too little to me

**Comment by dev-101** [comment]
Thanks

Well, maybe some general diagnostic page (or plugin, maybe) could be in handy, under Admin > Tools section. But, as you said, there are is not much to check for.
