### ISSUE TITLE
Potential security exploit using phpmailer

### ISSUE THREAD

**Issue by DeveloperChris** [osclass/Osclass#2099]
osclass uses phpmailer which has been shown to have a major exploit which can give an attacker easy control over an istallation.
It allows for file injection into the document root.

I do not believe osclass core is susceptible but I have not fully tested, and would need to conduct in depth tests. 
But plugins using the mailer system may well be susceptible. 

In my opinion this means phpmailer should be updated and a new version of osclass released as a priority.

details on the exploit and some test code can be found here
https://legalhackers.com/advisories/PHPMailer-Exploit-Remote-Code-Exec-CVE-2016-10033-Vuln.html

**Comment by dev-101** [comment]
Hi Chris,
thanks for reporting this. Osclass team should definitely consider upgrade asap / just to be safe.

But, (this is big *but* since upfront I am not a security expert), there are few internal mechanism in Osclass that could prevent this exploit from working (at least, in themes and core, plugins are separate matter):

(1) all fields are sanitized internally by at least some form of validation, in one of the demo exploit videos, attack works because of email input field, that should not pass currently in Osclass as a valid email - no way!

(2) $_GET, $_POST is sanitized too, so it should not work either.

Maybe I am not 100% correct for all cases, but it would be an extremely hard case specifically targeted at Osclass, if it is vulnerable.

Again, thanks!

**Comment by conejoninja** [comment]
Hi, thanks for contacting. We'll address this as soon as possible

**Comment by conejoninja** [comment]
Version updated of PHPMailer https://github.com/osclass/Osclass/commit/c7a886b4dc7314e5b2ddcb5b3700a99eab3d1fe8

**Comment by javsalgar** [comment]
Hi, do you have any ETA for this release?

**Comment by conejoninja** [comment]
Not a specific date yet, but probably this week. you could download head of hotfixes ( https://github.com/osclass/Osclass/archive/hotfixes.zip ), where it was already patched (but not tested)

**Comment by Tangol** [comment]
@conejoninja Any news about the official 3.7.2 release?
