### ISSUE TITLE
Categories language bug still exist

### ISSUE THREAD

**Issue by sxiii** [osclass/Osclass#2135]
Greetings. I've installed english version of Osclass, then added Russian, then created few categories and placed names for them in russian & english. When I go to the website, and press Russian or English, everything changes accordingly, *EXCEPT* the category names. This seems like an old bug from the past (2014)

http://forums.osclass.org/3-5-x/problem-with-language-of-categories!/

Also, I'd reinstalled russian version of osclass and then added english, and the bug repeats there.

Is it possible to fix?

Thanks.

**Comment by conejoninja** [comment]
We are not able to reproduce the issue, could you tell us in more detail (step by step) how to reproduce the issue. Or share some more details of your setup, maybe sharing a backup of your database, send it to desteban@osclass.org

**Comment by dev-101** [comment]
"Many" users have issues with this, every month or so pops a new topic @ forums.

teseo's fix https://github.com/osclass/Osclass/pull/1794 seems to be [still] working (but there are other proposals, maybe related to MariaDB).

**Comment by conejoninja** [comment]
Without a way to reproduce the issue, we can not merge Teseo's fix, since the indentation is different and the whole file is "changed" which makes difficult to see the differences. Since we can not check if it really fixes the problem and we can not see what is being changed, I asked for more information to reproduce this issue.
