### ISSUE TITLE
Improve script for france

### ISSUE THREAD

**Issue by zorodimanche** [osclass/Osclass#2165]
https://osclass.uservoice.com/forums/183966-general/suggestions/17660152-add-depatments-and-update-french-r%C3%A9gions-and-citie

**Comment by conejoninja** [comment]
It's already posted in uservoice, no need to post it here too. Plus github is for issues and bugs mostly, some improvements or features are welcome, but this one is too specific for France.

**Comment by zorodimanche** [comment]
So you are not going to do anything

**Comment by conejoninja** [comment]
You could use the cities table for department, and the city_area table for cities. Or create a new one with a plugin. The issue here is that other countries don't have departments, or have other location structure, for example Spain have "comunidades" that are bigger than regions. So if we one to make Osclass compatible with both (France and Spain). We need to make Country > comunidad > region > department > city 

What should appear on the select/dropdown menu of "comunidades" if you are in france? What should appear on "department" on Spain? We chose a more or less universal structure for locations: country > region > city. It may not work in every situation, but should be fine in most of them, also nothing is stopping you to not use it at all, or use something else if it doesn't fit you.

I'd like to remember you that Osclass is free and open source, if you want to make a PR about this we'll consider adding it.

**Comment by zorodimanche** [comment]
Would not it be interesting to add it and then everyone can either activate or deactivate from the backend comunidad> region> department.
