### ISSUE TITLE
I have many troubles of user and admin

### ISSUE THREAD

**Issue by kw3ku** [osclass/Osclass#2192]
User cannot login

Admin get log out 

listings are picking wrong images. 

some images are not showing, please help

**Comment by dev-101** [comment]
Please, for the sake of everyone here, use forum for support.

Each time you post something here, everyone receives an email, and this place is for issues with the core. It is extremely annoying.

Your issue is most probably hosting-related or something too specific to be posted here, unless you have identified the exact problem and know exactly what core function/code is wrong.

Forum is the place to ask help for these kind of issues **first**.

Osclass Team does not provide free support, unless it is related with the core, but you have to provide some evidence / proof that it is faulty in the first place.

Thank you.

**Comment by kw3ku** [comment]
sir, i have issues and i need help, be patient with me ;  here are some of my challenges; 

PHP Notice:  Undefined index: s_slug in /home7/oxglowne/public_html/oxglowcom/oc-includes/osclass/helpers/hSearch.php on line 442

DBConnectionClass::errorReport(): Couldn't fetch mysqli in /home7/oxglowne/public_html/oxglowcom/oc-includes/osclass/classes/database/DBConnectionClass.php on line 182

**Comment by kw3ku** [comment]
Array to string conversion in /home7/oxglowne/public_html/oxglowcom/oc-content/themes/new/includes/core-functions.php on line 52

**Comment by dev-101** [comment]
> PHP Notice: Undefined index: s_slug in /home7/oxglowne/public_html/oxglowcom/oc-includes/osclass/helpers/hSearch.php on line 442

You are missing slugs for your category names (that is what the notice above says). This is not a normal condition, unless you have some issues with non-lating languages. This is/was a known issue, not really sure if it was resolved or not.

> DBConnectionClass::...

Your MySQL server is down.

> Array to string conversion

Theme issue. Ask developer for help.

Again, all this is a perfect forum "material", not for GutHub repository named Osclass.

**Comment by kw3ku** [comment]
my final one; 

my admin panel   oc-admin    logs me out automatically, when i get in there too, i can't remove or delete users or anything. it doesn't take effect.

**Comment by dev-101** [comment]
I think Conejo already replied to you in another issue that you have problems with sessions. Sessions are key files that tells to PHP if a user is in logged-in state or not. You can google about PHP sessions and learn. Also, in forums you will find many solved tips and how to fix it.

**Comment by kw3ku** [comment]
I appreciate your support, its the hard way, but, i can't complain.
