### ISSUE TITLE
Plugin folder name .

### ISSUE THREAD

**Issue by web-media** [osclass/Osclass#2221]
We cannot guess plugin folder  name . 
Example : 
Short Name: list_seller_items
Folder name list_seller_items 
Short Name: AutoSearch
Plugin update URI: friendly-search-ajax-suggestions 
Folder Name : ajax_suggestions
Short Name: cars_plugin
Plugin update URI: cars-attributes
Plugin Folder Name cars_attributes   
  how can we find the path  of the plugin ? 
We should be more strict and somehow  restrict folder name to plugin short name .

**Comment by conejoninja** [comment]
wwe'll need some more info

**Comment by web-media** [comment]
Or other method to  be easy to guess  the path  based on plugin name
oc-content/plugins/plugin/file

**Comment by conejoninja** [comment]
```php
osc_plugin_folder(__FILE__) 
```

should do the trick unless there are symlinks involved

https://github.com/osclass/Osclass/blob/8b934905d07fe9f0d7fdb72de5bad743c5b31272/oc-includes/osclass/utils.php#L171

**Comment by web-media** [comment]
From  plugin  A y wanna include a  file from plugin : 
Short Name: mobile
Plugin update URI: osc-mobile 
 how do y find the path of the  mobile plugin ?

**Comment by conejoninja** [comment]
That's not a very good idea, but anyway, easiest and cleanest way is to define in plugin B something like PLUGIN_B_PATH and check if it's defined before using it. Or load directly in A since you need to know the exact path of the file inside plugin B. The name of the plugin's folder shouldn't change.


If you own plugin B, add a define, or some variable there to make it easy
If you don't own it, then load it anyway assuming the folder's name don't change (you still need the path of the file).
If you are loading the same file from every plugin, then just list the contents of oc-content/plugins and iterate over them.
You could list the installed/enabled plugins, (from t_preference) which will return the path to the index.php file of each plugin and clean it from there (using osc_plugin_folder)

**Comment by web-media** [comment]
More than that .  
cars_attribute plugin could be inside 
 long_plugin_folder_name_because_i_want_to_name_it_that_way  folder
5 plugins who iterate over 12  installed oc-content/plugins to include the "required"files , 
but to  present a list  of plugins to admin will bring  12  more iterations to get plugins names ,shortnames aka"osc_plugin_get_info($plugin)" means 24 iterations over oc-content/plugins or t_preference  not  to mention already done iterations "Plugins::loadActive()"   or other iterations from the "required" files
 should be  a Best practices plugin developer guide for naming  and file structure 
 should be  some methods to translate folder name to plugin short name and  plugin name
should be some classes (class CarsAttributes )   with plugin  info  to  easy to translate from plugin folder name to class name to find plugin name  
or
 ```php
Plugins::setInfo(array(
    'short_name'        =>  'cars_attributes', // should match folder name or
    'path'                 =>    'oc-content/plugins/folder_name', // plugin cars_attributes path
    'name'                 =>    __('Cars Attributes'),
    'description'         =>    __('The  plugin adds Cars ......'),
    'type'                  =>    'both',  //  front,back,both  options .. where to load ( we dont need admin
    'author'                =>    ' Author name',
    'version'               =>    '0.2.1',
    'website'               =>    'http://www.abc.org/',
    'require_osclass_version'  =>    '3.7.3'
   
));
```
should be  more ways  for plugins to communicate with  other plugins
Etc...
Etc... 
Thanks
